### ISSUE TITLE
Make it more clear about the output format

### ISSUE THREAD

**Issue by TimHe95** [zakimjz/SLEUTH#1]
Could you please explain more about the output format:  
Running `./sleuth -i testcase3.asc -s 0.5 -o -O`, I got:  
```
DBASE_NUM_TRANS : 3
DBASE_MAXITEM : 6
MINSUPPORT : 2 (0.5)
1 - 3
2 - 3
3 - 3
4 - 3
1 2  - 3
1 2 -1 4  - 2
1 3  - 2
1 3 -1 2  - 2
1 3 -1 4  - 2
1 4  - 3
2 4  - 2
F1 - 4 6
F2 - 4 16
F3 - 3 20
F4 - 0 10
[ 1 6 4 5.00679e-05 0 ] [ 2 16 4 3.09944e-05 0 ] [ 3 20 3 1.50204e-05 0 ] [ 4 10 0 3.09944e-06 0 ] [ SUM 52 11 9.91821e-05 ] 0.000192881
TIME = 0.000192881
BrachIt = 104
```
I guess the frequent subtrees are shown from 4th line to 14th line (with frequency behind  '-') but not in the format in the paper (i.e., `(1 2 -1)`).

What is the meaning of `DBASE_MAXITEM`, `F1`-`F4`, `[...]`, `TIME`(execution time in hour?day?), `BrachIt`

Thanks.

**Comment by zakimjz** [comment]
I have added the output format

**Comment by zakimjz** [comment]
The branchIt is -1 as described in the paper. In the internal working, I replace it with the highest item id, but it is printed as -1 in the output. You can ignore this.
