### ISSUE TITLE
Support to specify the max depth of a "embedded tree"

### ISSUE THREAD

**Issue by TimHe95** [zakimjz/SLEUTH#2]
I have 5 different forests.
I want to find correlations with sub-tree and forests (e.g., when I observed `1 3 -1 2 -1 4`, I believe it is in forest No.2).

But the support of some sub-trees and forests is low, I have to use a low `-s`(e.g., 0.1). Thus, `sleuth` will run indefinitely (without `-I`).

However, the lift of such correlation is high, (e.g., when I observe a palm tree in a forest, I am 100% sure it is in a tropical forest rather than a forest in Russia. However, there are only 10% trees in tropical forest that are palm trees) the correlation is still valuable.

Therefore, if I can specify a swallow embedded sub-tree, the execution time may be much shorter.

Thanks.

**Comment by zakimjz** [comment]
Should not be hard to add a "depth" check in enumerate_freq function. I am not actively supporting this, since the aim is to provide the implementation of the original paper. Feel free to add such support.
